/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ass.ui;

import javax.swing.JMenuItem;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.JButton;

/**
 *
 * @author Littlekey
 */
public class Main extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Main() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		pnlUsers = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		lisUsers = new javax.swing.JList();
		lblUserId1 = new javax.swing.JLabel();
		lblUserGroup1 = new javax.swing.JLabel();
		lblTitle1 = new javax.swing.JLabel();
		lblSex1 = new javax.swing.JLabel();
		lblLastName1 = new javax.swing.JLabel();
		lblFirstName1 = new javax.swing.JLabel();
		lblDOB1 = new javax.swing.JLabel();
		jLabel8 = new javax.swing.JLabel();
		jLabel9 = new javax.swing.JLabel();
		jLabel10 = new javax.swing.JLabel();
		jLabel11 = new javax.swing.JLabel();
		jLabel12 = new javax.swing.JLabel();
		txtUserId1 = new javax.swing.JTextField();
		cbxUserGroup1 = new javax.swing.JComboBox();
		txtTitle1 = new javax.swing.JTextField();
		txtSex1 = new javax.swing.JTextField();
		txtLastName1 = new javax.swing.JTextField();
		txtFirstName1 = new javax.swing.JTextField();
		txtDOB = new javax.swing.JTextField();
		jTextField7 = new javax.swing.JTextField();
		jTextField8 = new javax.swing.JTextField();
		jTextField9 = new javax.swing.JTextField();
		jTextField10 = new javax.swing.JTextField();
		jTextField11 = new javax.swing.JTextField();
		jButton1 = new javax.swing.JButton();
		jButton2 = new javax.swing.JButton();
		jButton3 = new javax.swing.JButton();
		jButton4 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		jLabel24 = new javax.swing.JLabel();
		jLabel25 = new javax.swing.JLabel();
		jLabel26 = new javax.swing.JLabel();
		jTextField22 = new javax.swing.JTextField();
		jTextField23 = new javax.swing.JTextField();
		jTextField24 = new javax.swing.JTextField();
		jButton9 = new javax.swing.JButton();
		jLabel27 = new javax.swing.JLabel();
		jScrollPane3 = new javax.swing.JScrollPane();
		jTable2 = new javax.swing.JTable();
		jButton10 = new javax.swing.JButton();
		jButton11 = new javax.swing.JButton();
		jLabel28 = new javax.swing.JLabel();
		jLabel29 = new javax.swing.JLabel();
		jLabel30 = new javax.swing.JLabel();
		jTextField25 = new javax.swing.JTextField();
		jTextField26 = new javax.swing.JTextField();
		jButton12 = new javax.swing.JButton();
		jScrollPane4 = new javax.swing.JScrollPane();
		jTable3 = new javax.swing.JTable();
		jLabel31 = new javax.swing.JLabel();
		jLabel32 = new javax.swing.JLabel();
		jLabel33 = new javax.swing.JLabel();
		jLabel34 = new javax.swing.JLabel();
		jLabel35 = new javax.swing.JLabel();
		jLabel36 = new javax.swing.JLabel();
		jLabel37 = new javax.swing.JLabel();
		jLabel38 = new javax.swing.JLabel();
		jLabel39 = new javax.swing.JLabel();
		jLabel40 = new javax.swing.JLabel();
		jLabel41 = new javax.swing.JLabel();
		jLabel42 = new javax.swing.JLabel();
		jLabel43 = new javax.swing.JLabel();
		jLabel44 = new javax.swing.JLabel();
		jLabel45 = new javax.swing.JLabel();
		jPanel4 = new javax.swing.JPanel();
		jLabel46 = new javax.swing.JLabel();
		jLabel47 = new javax.swing.JLabel();
		jLabel48 = new javax.swing.JLabel();
		jTextField27 = new javax.swing.JTextField();
		jTextField28 = new javax.swing.JTextField();
		jButton13 = new javax.swing.JButton();
		jScrollPane5 = new javax.swing.JScrollPane();
		jTable4 = new javax.swing.JTable();
		jLabel49 = new javax.swing.JLabel();
		jLabel50 = new javax.swing.JLabel();
		jLabel51 = new javax.swing.JLabel();
		jLabel52 = new javax.swing.JLabel();
		jLabel53 = new javax.swing.JLabel();
		jTextField29 = new javax.swing.JTextField();
		jTextField30 = new javax.swing.JTextField();
		jTextField31 = new javax.swing.JTextField();
		jButton14 = new javax.swing.JButton();
		jScrollPane6 = new javax.swing.JScrollPane();
		jTable5 = new javax.swing.JTable();
		jLabel54 = new javax.swing.JLabel();
		jLabel55 = new javax.swing.JLabel();
		jLabel56 = new javax.swing.JLabel();
		jLabel57 = new javax.swing.JLabel();
		jLabel58 = new javax.swing.JLabel();
		jLabel59 = new javax.swing.JLabel();
		jLabel60 = new javax.swing.JLabel();
		jScrollPane7 = new javax.swing.JScrollPane();
		jTable6 = new javax.swing.JTable();
		jButton15 = new javax.swing.JButton();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jPanel5 = new javax.swing.JPanel();
		jLabel61 = new javax.swing.JLabel();
		jLabel62 = new javax.swing.JLabel();
		jLabel63 = new javax.swing.JLabel();
		jLabel64 = new javax.swing.JLabel();
		jLabel65 = new javax.swing.JLabel();
		jButton18 = new javax.swing.JButton();
		jButton19 = new javax.swing.JButton();
		jButton20 = new javax.swing.JButton();
		jButton21 = new javax.swing.JButton();
		jButton22 = new javax.swing.JButton();
		jTextField32 = new javax.swing.JTextField();
		jTextField33 = new javax.swing.JTextField();
		jTextField34 = new javax.swing.JTextField();
		jTextField35 = new javax.swing.JTextField();
		jTextField36 = new javax.swing.JTextField();
		jLabel66 = new javax.swing.JLabel();
		jMenuBar1 = new javax.swing.JMenuBar();
		menuAbout = new javax.swing.JMenu();
		jMenu4 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Library Management System");

		lisUsers.setModel(new javax.swing.AbstractListModel() {
			String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4",
					"Item 5" };

			public int getSize() {
				return strings.length;
			}

			public Object getElementAt(int i) {
				return strings[i];
			}
		});
		jScrollPane1.setViewportView(lisUsers);

		lblUserId1.setText("User ID:");
		lblUserId1.setName(""); // NOI18N

		lblUserGroup1.setText("User Group:");

		lblTitle1.setText("Title:");

		lblSex1.setText("Sex:");

		lblLastName1.setText("Last Name:");

		lblFirstName1.setText("First Name:");

		lblDOB1.setText("Date of Birth:");

		jLabel8.setText("Address:");

		jLabel9.setText("Email:");

		jLabel10.setText("Phone:");

		jLabel11.setText("User Group:");

		jLabel12.setText("Password:");

		txtUserId1.setText("jTextField1");

		cbxUserGroup1.setModel(new javax.swing.DefaultComboBoxModel(
				new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

		txtTitle1.setText("jTextField2");

		txtSex1.setText("jTextField3");

		txtLastName1.setText("jTextField4");

		txtFirstName1.setText("jTextField5");

		txtDOB.setText("jTextField6");

		jTextField7.setText("jTextField7");

		jTextField8.setText("jTextField8");

		jTextField9.setText("jTextField9");

		jTextField10.setText("jTextField10");

		jTextField11.setText("jTextField11");

		jButton1.setText("Add User");
		jButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton1ActionPerformed(evt);
			}
		});

		jButton2.setText("Update User");

		jButton3.setText("Delete User");

		jButton4.setText("Search User");

		javax.swing.GroupLayout gl_pnlUsers = new javax.swing.GroupLayout(
				pnlUsers);
		pnlUsers.setLayout(gl_pnlUsers);
		gl_pnlUsers
				.setHorizontalGroup(gl_pnlUsers
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_pnlUsers
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												197,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(68, 68, 68)
										.addGroup(
												gl_pnlUsers
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addGroup(
																gl_pnlUsers
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.LEADING)
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				gl_pnlUsers
																						.createSequentialGroup()
																						.addGroup(
																								gl_pnlUsers
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(
																												lblSex1)
																										.addComponent(
																												lblLastName1)
																										.addComponent(
																												lblTitle1)
																										.addComponent(
																												lblUserGroup1)
																										.addComponent(
																												lblUserId1))
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addGroup(
																								gl_pnlUsers
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.LEADING)
																										.addComponent(
																												txtLastName1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												150,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												txtSex1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												96,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												txtTitle1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												96,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												cbxUserGroup1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												96,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addComponent(
																												txtUserId1,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												96,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																		.addGroup(
																				gl_pnlUsers
																						.createSequentialGroup()
																						.addComponent(
																								jButton1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								98,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGap(28,
																								28,
																								28)
																						.addComponent(
																								jButton2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								98,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING,
																				gl_pnlUsers
																						.createSequentialGroup()
																						.addComponent(
																								lblFirstName1)
																						.addPreferredGap(
																								javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																						.addComponent(
																								txtFirstName1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								149,
																								javax.swing.GroupLayout.PREFERRED_SIZE)))
														.addGroup(
																gl_pnlUsers
																		.createSequentialGroup()
																		.addComponent(
																				lblDOB1)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addComponent(
																				txtDOB,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				149,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addGroup(
												gl_pnlUsers
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																gl_pnlUsers
																		.createSequentialGroup()
																		.addGap(32,
																				32,
																				32)
																		.addComponent(
																				jButton3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				98,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(29,
																				29,
																				29)
																		.addComponent(
																				jButton4,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				98,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																gl_pnlUsers
																		.createSequentialGroup()
																		.addGap(40,
																				40,
																				40)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jLabel12))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								149,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								149,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								118,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								118,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								118,
																								javax.swing.GroupLayout.PREFERRED_SIZE))))
										.addContainerGap(285, Short.MAX_VALUE)));
		gl_pnlUsers
				.setVerticalGroup(gl_pnlUsers
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								gl_pnlUsers
										.createSequentialGroup()
										.addGap(15, 15, 15)
										.addGroup(
												gl_pnlUsers
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																jScrollPane1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																343,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																gl_pnlUsers
																		.createSequentialGroup()
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								txtUserId1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblUserId1))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								lblUserGroup1)
																						.addComponent(
																								cbxUserGroup1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel8)
																						.addComponent(
																								jTextField7,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								lblTitle1)
																						.addComponent(
																								txtTitle1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel9)
																						.addComponent(
																								jTextField8,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								txtSex1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblSex1)
																						.addComponent(
																								jLabel10)
																						.addComponent(
																								jTextField9,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel11)
																						.addComponent(
																								jTextField10,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								txtLastName1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblLastName1))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jTextField11,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jLabel12)
																						.addComponent(
																								txtFirstName1,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblFirstName1))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				gl_pnlUsers
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								txtDOB,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								lblDOB1))
																		.addGap(53,
																				53,
																				53)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												132, Short.MAX_VALUE)
										.addGroup(
												gl_pnlUsers
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																37,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton2,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																41,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton3,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																41,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton4,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																38,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap()));

		jTabbedPane1.addTab("Users", pnlUsers);

		jLabel23.setText("Search Book:");

		jLabel24.setText("Book ID:");

		jLabel25.setText("Title:");

		jLabel26.setText("Author:");

		jTextField22.setText("jTextField22");

		jTextField23.setText("jTextField23");

		jTextField24.setText("jTextField24");

		jButton9.setText("Search Book");

		jLabel27.setText("Search Result:");

		jTable2.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null }, { null, null, null },
						{ null, null, null }, { null, null, null } },
				new String[] { "Book ID", "Title", "Author" }));
		jScrollPane3.setViewportView(jTable2);

		jButton10.setText("Borrow Books");
		jButton10.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton10ActionPerformed(evt);
			}
		});

		jButton11.setText("Return Books");
		jButton11.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton11ActionPerformed(evt);
			}
		});
		pnlBooks = new javax.swing.JPanel();
		lblBookId = new javax.swing.JLabel();
		lblSerialNumber = new javax.swing.JLabel();
		lblTitle2 = new javax.swing.JLabel();
		lblAuthor = new javax.swing.JLabel();
		lblPublisher = new javax.swing.JLabel();
		lblSubject = new javax.swing.JLabel();
		lblPages = new javax.swing.JLabel();
		lblSeries = new javax.swing.JLabel();
		lblPrice = new javax.swing.JLabel();
		lblStatus = new javax.swing.JLabel();
		txtBookId = new javax.swing.JTextField();
		txtSerialNumber = new javax.swing.JTextField();
		txtTitle2 = new javax.swing.JTextField();
		txtAuthor = new javax.swing.JTextField();
		txtPublisher = new javax.swing.JTextField();
		txtSubject = new javax.swing.JTextField();
		txtPages = new javax.swing.JTextField();
		txtSeries = new javax.swing.JTextField();
		txtPrice = new javax.swing.JTextField();
		txtStatus = new javax.swing.JTextField();
		btnAddBook = new javax.swing.JButton();
		btnEditBook = new javax.swing.JButton();
		btnSearchBook = new javax.swing.JButton();
		btnDeleteBook = new javax.swing.JButton();
		
		Object[][] data = new Object[5][8];
		
		for (int i = 0; i < data.length; i++) {
			data[i][0] = 1;
			data[i][1] = 2;
			data[i][2] = "Book Title";
			data[i][3] = "Book Title";
			data[i][4] = "Book Title";
			data[i][5] = 100;
			data[i][6] = 5.0;
			data[i][7] = true;
			
		}

		lblBookId.setText("Book ID:");

		lblSerialNumber.setText("Serial Number:");

		lblTitle2.setText("Title:");

		lblAuthor.setText("Author:");

		lblPublisher.setText("Publisher:");

		lblSubject.setText("Subject:");

		lblPages.setText("Pages:");

		lblSeries.setText("Series:");

		lblPrice.setText("Price:");

		lblStatus.setText("Status:");

		txtBookId.setText("jTextField12");

		txtSerialNumber.setText("jTextField13");

		txtTitle2.setText("jTextField14");

		txtAuthor.setText("jTextField15");

		txtPublisher.setText("jTextField16");

		txtSubject.setText("jTextField17");

		txtPages.setText("jTextField18");

		txtSeries.setText("jTextField19");

		txtPrice.setText("jTextField20");

		txtStatus.setText("jTextField21");

		btnAddBook.setText("Add Book");
		btnAddBook.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				DBConnection db = new DBConnection();
				db.openConn();
				db.addBook(Double.parseDouble(txtPrice.getText()), "Available", 
						Integer.parseInt(txtSerialNumber.getText()), 
						txtSeries.getText(), txtTitle2.getText(), 
						txtPublisher.getText(), txtPages.getText(), 
						txtSubject.getText(), txtBookId.getText(), 
						txtAuthor.getText());
				db.closeConn();
			}
		});

		btnEditBook.setText("Edit Book");

		btnSearchBook.setText("Search Book");

		btnDeleteBook.setText("Delete Book");
		
		JButton btnAddBook_1 = new JButton("Add Book");

		javax.swing.GroupLayout gl_pnlBooks = new javax.swing.GroupLayout(
				pnlBooks);
		gl_pnlBooks.setHorizontalGroup(
			gl_pnlBooks.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_pnlBooks.createSequentialGroup()
					.addGap(35)
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.TRAILING)
						.addGroup(gl_pnlBooks.createSequentialGroup()
							.addComponent(lblBookId)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(txtBookId, GroupLayout.PREFERRED_SIZE, 157, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_pnlBooks.createSequentialGroup()
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.TRAILING)
								.addComponent(lblTitle2)
								.addComponent(lblSerialNumber)
								.addComponent(lblAuthor)
								.addComponent(lblPublisher))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING, false)
								.addComponent(txtSerialNumber, GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
								.addComponent(txtTitle2)
								.addComponent(txtAuthor)
								.addComponent(txtPublisher))))
					.addGap(76)
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING, false)
						.addGroup(gl_pnlBooks.createSequentialGroup()
							.addComponent(lblSubject)
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addComponent(txtSubject, GroupLayout.PREFERRED_SIZE, 155, GroupLayout.PREFERRED_SIZE))
						.addGroup(gl_pnlBooks.createSequentialGroup()
							.addGap(4)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.TRAILING)
								.addComponent(lblSeries)
								.addComponent(lblPages)
								.addComponent(lblPrice)
								.addComponent(lblStatus))
							.addPreferredGap(ComponentPlacement.UNRELATED)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING)
								.addComponent(txtPages)
								.addComponent(txtSeries)
								.addComponent(txtPrice)
								.addComponent(txtStatus))))
					.addGap(150)
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING)
						.addGroup(gl_pnlBooks.createSequentialGroup()
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING, false)
								.addComponent(btnSearchBook, GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE)
								.addComponent(btnAddBook, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
							.addGap(55)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING, false)
								.addComponent(btnDeleteBook, GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
								.addComponent(btnEditBook, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
						.addComponent(btnAddBook_1))
					.addContainerGap(84, Short.MAX_VALUE))
		);
		gl_pnlBooks.setVerticalGroup(
			gl_pnlBooks.createParallelGroup(Alignment.LEADING)
				.addGroup(gl_pnlBooks.createSequentialGroup()
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING, false)
						.addGroup(gl_pnlBooks.createSequentialGroup()
							.addGap(171)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblBookId)
								.addComponent(lblSubject)
								.addComponent(txtBookId, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtSubject, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblSerialNumber)
								.addComponent(lblPages)
								.addComponent(txtSerialNumber, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtPages, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18)
							.addGroup(gl_pnlBooks.createParallelGroup(Alignment.BASELINE)
								.addComponent(lblTitle2)
								.addComponent(lblSeries)
								.addComponent(txtTitle2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
								.addComponent(txtSeries, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
							.addGap(18))
						.addGroup(Alignment.TRAILING, gl_pnlBooks.createSequentialGroup()
							.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
							.addComponent(btnAddBook_1)
							.addGap(32)))
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblAuthor)
						.addComponent(lblPrice)
						.addComponent(txtAuthor, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtPrice, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnAddBook, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE)
						.addComponent(btnEditBook, GroupLayout.PREFERRED_SIZE, 33, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.RELATED)
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.BASELINE)
						.addComponent(lblPublisher)
						.addComponent(lblStatus)
						.addComponent(txtPublisher, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
						.addComponent(txtStatus, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
					.addPreferredGap(ComponentPlacement.UNRELATED)
					.addGroup(gl_pnlBooks.createParallelGroup(Alignment.LEADING, false)
						.addComponent(btnDeleteBook, GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
						.addComponent(btnSearchBook, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
					.addContainerGap(150, Short.MAX_VALUE))
		);
		pnlBooks.setLayout(gl_pnlBooks);

		jTabbedPane1.addTab("Books", pnlBooks);

		jLabel28.setText("Search User: ");

		jLabel29.setText("User ID:");

		jLabel30.setText("Name:");

		jTextField25.setText("jTextField25");

		jTextField26.setText("jTextField26");

		jButton12.setText("Search User");

		jTable3.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null },
						{ null, null }, { null, null } }, new String[] {
						"User ID", "Name" }));
		jScrollPane4.setViewportView(jTable3);

		jLabel31.setText("Order Details:");

		jLabel32.setText("User ID:");

		jLabel33.setText("Name:");

		jLabel34.setText("Book ID:");

		jLabel35.setText("Title:");

		jLabel36.setText("Author:");

		jLabel37.setText("Borrow Date:");

		jLabel38.setText("Return Date:");

		jLabel39.setText("jLabel39");

		jLabel40.setText("jLabel40");

		jLabel41.setText("jLabel41");

		jLabel42.setText("jLabel42");

		jLabel43.setText("jLabel43");

		jLabel44.setText("jLabel44");

		jLabel45.setText("jLabel45");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout
				.setHorizontalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jLabel23)
																										.addGap(439,
																												439,
																												439)
																										.addComponent(
																												jLabel28))
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel30)
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addComponent(
																																								jLabel25)
																																						.addComponent(
																																								jLabel26)
																																						.addComponent(
																																								jLabel24))
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								false)
																																						.addComponent(
																																								jTextField22)
																																						.addComponent(
																																								jTextField23)
																																						.addComponent(
																																								jTextField24,
																																								javax.swing.GroupLayout.PREFERRED_SIZE,
																																								169,
																																								javax.swing.GroupLayout.PREFERRED_SIZE))
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addGap(282,
																																												282,
																																												282)
																																										.addComponent(
																																												jLabel29))
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addGap(37,
																																												37,
																																												37)
																																										.addComponent(
																																												jButton9,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												113,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
																										.addGap(18,
																												18,
																												18)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																jTextField25,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																146,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField26))))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addComponent(
																				jButton12,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				129,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(134,
																				134,
																				134))
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel27)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jScrollPane3,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																394,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addComponent(
																																				jButton10,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				114,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(43,
																																				43,
																																				43)
																																		.addComponent(
																																				jButton11,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				115,
																																				javax.swing.GroupLayout.PREFERRED_SIZE)
																																		.addGap(78,
																																				78,
																																				78)))
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addGap(31,
																																				31,
																																				31)
																																		.addComponent(
																																				jScrollPane4,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				555,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addGap(42,
																																				42,
																																				42)
																																		.addComponent(
																																				jLabel31))
																														.addGroup(
																																jPanel3Layout
																																		.createSequentialGroup()
																																		.addGap(43,
																																				43,
																																				43)
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING)
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addGroup(
																																												jPanel3Layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.TRAILING)
																																														.addComponent(
																																																jLabel33)
																																														.addComponent(
																																																jLabel32))
																																										.addGap(18,
																																												18,
																																												18)
																																										.addGroup(
																																												jPanel3Layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING)
																																														.addComponent(
																																																jLabel39)
																																														.addComponent(
																																																jLabel40)))
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addGroup(
																																												jPanel3Layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.TRAILING)
																																														.addComponent(
																																																jLabel35)
																																														.addComponent(
																																																jLabel34))
																																										.addGap(18,
																																												18,
																																												18)
																																										.addGroup(
																																												jPanel3Layout
																																														.createParallelGroup(
																																																javax.swing.GroupLayout.Alignment.LEADING)
																																														.addComponent(
																																																jLabel41)
																																														.addComponent(
																																																jLabel42))))
																																		.addGap(218,
																																				218,
																																				218)
																																		.addGroup(
																																				jPanel3Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.TRAILING)
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel38)
																																										.addGap(18,
																																												18,
																																												18)
																																										.addComponent(
																																												jLabel45))
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel36)
																																										.addGap(18,
																																												18,
																																												18)
																																										.addComponent(
																																												jLabel43))
																																						.addGroup(
																																								jPanel3Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel37)
																																										.addGap(18,
																																												18,
																																												18)
																																										.addComponent(
																																												jLabel44)))))))
																		.addContainerGap(
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))));
		jPanel3Layout
				.setVerticalGroup(jPanel3Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel3Layout
										.createSequentialGroup()
										.addGap(29, 29, 29)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel23)
														.addComponent(jLabel28))
										.addGap(13, 13, 13)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel24)
														.addComponent(
																jTextField22,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel29)
														.addComponent(
																jTextField26,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(7, 7, 7)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel25)
														.addComponent(
																jTextField23,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel30)
														.addComponent(
																jTextField25,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jTextField24,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton9)
																		.addComponent(
																				jButton12))
														.addComponent(jLabel26))
										.addGap(18, 18, 18)
										.addComponent(jLabel27)
										.addGroup(
												jPanel3Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel3Layout
																		.createSequentialGroup()
																		.addGap(30,
																				30,
																				30)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel3Layout
																										.createSequentialGroup()
																										.addComponent(
																												jScrollPane4,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												112,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(18,
																												18,
																												18)
																										.addComponent(
																												jLabel31)
																										.addGap(18,
																												18,
																												18)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel32)
																														.addComponent(
																																jLabel39))
																										.addGap(18,
																												18,
																												18)
																										.addGroup(
																												jPanel3Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.BASELINE)
																														.addComponent(
																																jLabel33)
																														.addComponent(
																																jLabel40)
																														.addComponent(
																																jLabel36)
																														.addComponent(
																																jLabel43)))
																						.addComponent(
																								jScrollPane3,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								208,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel34)
																						.addComponent(
																								jLabel41)
																						.addComponent(
																								jLabel37)
																						.addComponent(
																								jLabel44))
																		.addGap(17,
																				17,
																				17)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel35)
																						.addComponent(
																								jLabel42)
																						.addComponent(
																								jLabel38)
																						.addComponent(
																								jLabel45))
																		.addContainerGap(
																				77,
																				Short.MAX_VALUE))
														.addGroup(
																javax.swing.GroupLayout.Alignment.TRAILING,
																jPanel3Layout
																		.createSequentialGroup()
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)
																		.addGroup(
																				jPanel3Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton11)
																						.addComponent(
																								jButton10))
																		.addGap(75,
																				75,
																				75)))));

		jTabbedPane1.addTab("Books Orders", jPanel3);

		jLabel46.setText("Search User:");

		jLabel47.setText("User ID:");

		jLabel48.setText("Name:");

		jTextField27.setText("jTextField27");

		jTextField28.setText("jTextField28");

		jButton13.setText("Search User");

		jTable4.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null }, { null, null },
						{ null, null }, { null, null } }, new String[] {
						"User ID:", "Name:" }));
		jScrollPane5.setViewportView(jTable4);

		jLabel49.setText("Result:");

		jLabel50.setText("Search Books:");

		jLabel51.setText("Book ID:");

		jLabel52.setText("Title:");

		jLabel53.setText("Author:");

		jTextField29.setText("jTextField29");

		jTextField30.setText("jTextField30");

		jTextField31.setText("jTextField31");

		jButton14.setText("Search Book");

		jTable5.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane6.setViewportView(jTable5);

		jLabel54.setText("Record details:");

		jLabel55.setText("User ID:");

		jLabel56.setText("Name:");

		jLabel57.setText("Fines Due:");

		jLabel58.setText("jLabel58");

		jLabel59.setText("jLabel59");

		jLabel60.setText("jLabel60");

		jTable6.setModel(new javax.swing.table.DefaultTableModel(
				new Object[][] { { null, null, null, null },
						{ null, null, null, null }, { null, null, null, null },
						{ null, null, null, null } }, new String[] { "Title 1",
						"Title 2", "Title 3", "Title 4" }));
		jScrollPane7.setViewportView(jTable6);

		jButton15.setText("Print Receipt");

		jButton16.setText("Update Record");

		jButton17.setText("Fines");

		javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(
				jPanel4);
		jPanel4.setLayout(jPanel4Layout);
		jPanel4Layout
				.setHorizontalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.TRAILING)
																		.addComponent(
																				jScrollPane6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				439,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addGroup(
																												jPanel4Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addGroup(
																																jPanel4Layout
																																		.createSequentialGroup()
																																		.addGroup(
																																				jPanel4Layout
																																						.createParallelGroup(
																																								javax.swing.GroupLayout.Alignment.LEADING,
																																								false)
																																						.addComponent(
																																								jLabel46)
																																						.addGroup(
																																								jPanel4Layout
																																										.createSequentialGroup()
																																										.addGap(9,
																																												9,
																																												9)
																																										.addComponent(
																																												jLabel48)
																																										.addGap(18,
																																												18,
																																												18)
																																										.addComponent(
																																												jTextField28))
																																						.addGroup(
																																								jPanel4Layout
																																										.createSequentialGroup()
																																										.addComponent(
																																												jLabel47)
																																										.addGap(18,
																																												18,
																																												18)
																																										.addComponent(
																																												jTextField27,
																																												javax.swing.GroupLayout.PREFERRED_SIZE,
																																												142,
																																												javax.swing.GroupLayout.PREFERRED_SIZE)))
																																		.addGap(40,
																																				40,
																																				40)
																																		.addComponent(
																																				jButton13))
																														.addComponent(
																																jLabel49)))
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addGap(19,
																												19,
																												19)
																										.addComponent(
																												jScrollPane5,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												439,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addContainerGap()
																										.addComponent(
																												jLabel50))))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel4Layout
																										.createParallelGroup(
																												javax.swing.GroupLayout.Alignment.TRAILING)
																										.addComponent(
																												jLabel52)
																										.addComponent(
																												jLabel51))
																						.addComponent(
																								jLabel53))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jTextField29,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								141,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jTextField30,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								141,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addGroup(
																								jPanel4Layout
																										.createSequentialGroup()
																										.addComponent(
																												jTextField31,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												141,
																												javax.swing.GroupLayout.PREFERRED_SIZE)
																										.addGap(49,
																												49,
																												49)
																										.addComponent(
																												jButton14,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												91,
																												javax.swing.GroupLayout.PREFERRED_SIZE)))))
										.addGap(50, 50, 50)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jLabel54)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING)
																						.addComponent(
																								jLabel56)
																						.addComponent(
																								jLabel55)
																						.addComponent(
																								jLabel57))
																		.addGap(18,
																				18,
																				18)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jLabel58)
																						.addComponent(
																								jLabel59)
																						.addComponent(
																								jLabel60)))
														.addComponent(
																jScrollPane7,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																506,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jButton15)
																		.addGap(61,
																				61,
																				61)
																		.addComponent(
																				jButton16)
																		.addGap(77,
																				77,
																				77)
																		.addComponent(
																				jButton17,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				78,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(35, Short.MAX_VALUE)));
		jPanel4Layout
				.setVerticalGroup(jPanel4Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel4Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel46)
														.addComponent(
																jLabel54,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																20,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel47)
														.addComponent(
																jTextField27,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(jLabel55)
														.addComponent(jLabel58))
										.addGap(18, 18, 18)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel48)
																		.addComponent(
																				jTextField28,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addComponent(
																				jButton13))
														.addGroup(
																jPanel4Layout
																		.createParallelGroup(
																				javax.swing.GroupLayout.Alignment.BASELINE)
																		.addComponent(
																				jLabel56)
																		.addComponent(
																				jLabel59)))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel49)
														.addComponent(jLabel57)
														.addComponent(jLabel60))
										.addGap(10, 10, 10)
										.addGroup(
												jPanel4Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane7,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				266,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(48,
																				48,
																				48)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jButton15)
																						.addComponent(
																								jButton16)
																						.addComponent(
																								jButton17)))
														.addGroup(
																jPanel4Layout
																		.createSequentialGroup()
																		.addComponent(
																				jScrollPane5,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				112,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jLabel50)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel51)
																						.addComponent(
																								jTextField29,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel52)
																						.addComponent(
																								jTextField30,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE))
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addGroup(
																				jPanel4Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.BASELINE)
																						.addComponent(
																								jLabel53)
																						.addComponent(
																								jTextField31,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jButton14))
																		.addGap(18,
																				18,
																				18)
																		.addComponent(
																				jScrollPane6,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				130,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));

		jTabbedPane1.addTab("Records", jPanel4);

		jLabel61.setText("Daily Report:");

		jLabel62.setText("Monthly Report:");

		jLabel63.setText("Annually Report:");

		jLabel64.setText("Fines Report:");

		jLabel65.setText("Book Purchase Report:");

		jButton18.setText("Generate");

		jButton19.setText("Generate");

		jButton20.setText("Generate");

		jButton21.setText("Generate");

		jButton22.setText("Generate");

		jTextField32.setText("jTextField32");

		jTextField33.setText("jTextField33");

		jTextField34.setText("jTextField34");

		jTextField35.setText("jTextField35");

		jTextField36.setText("jTextField36");

		jLabel66.setText("Save to:");

		javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(
				jPanel5);
		jPanel5.setLayout(jPanel5Layout);
		jPanel5Layout
				.setHorizontalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																jPanel5Layout
																		.createSequentialGroup()
																		.addGroup(
																				jPanel5Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addGroup(
																								jPanel5Layout
																										.createSequentialGroup()
																										.addGap(62,
																												62,
																												62)
																										.addGroup(
																												jPanel5Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel63)
																														.addComponent(
																																jLabel62)
																														.addComponent(
																																jLabel61)))
																						.addGroup(
																								jPanel5Layout
																										.createSequentialGroup()
																										.addGap(32,
																												32,
																												32)
																										.addGroup(
																												jPanel5Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addComponent(
																																jLabel65)
																														.addComponent(
																																jLabel64))))
																		.addGap(52,
																				52,
																				52)
																		.addGroup(
																				jPanel5Layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING,
																								false)
																						.addGroup(
																								jPanel5Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel5Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jTextField35,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																261,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField36))
																										.addGroup(
																												jPanel5Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.TRAILING)
																														.addGroup(
																																jPanel5Layout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				jButton22,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				129,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))
																														.addGroup(
																																jPanel5Layout
																																		.createSequentialGroup()
																																		.addPreferredGap(
																																				javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																																				javax.swing.GroupLayout.DEFAULT_SIZE,
																																				Short.MAX_VALUE)
																																		.addComponent(
																																				jButton21,
																																				javax.swing.GroupLayout.PREFERRED_SIZE,
																																				129,
																																				javax.swing.GroupLayout.PREFERRED_SIZE))))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel5Layout
																										.createSequentialGroup()
																										.addComponent(
																												jTextField34)
																										.addPreferredGap(
																												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																										.addComponent(
																												jButton20,
																												javax.swing.GroupLayout.PREFERRED_SIZE,
																												129,
																												javax.swing.GroupLayout.PREFERRED_SIZE))
																						.addGroup(
																								javax.swing.GroupLayout.Alignment.TRAILING,
																								jPanel5Layout
																										.createSequentialGroup()
																										.addGroup(
																												jPanel5Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING,
																																false)
																														.addComponent(
																																jTextField33,
																																javax.swing.GroupLayout.DEFAULT_SIZE,
																																261,
																																Short.MAX_VALUE)
																														.addComponent(
																																jTextField32))
																										.addGap(6,
																												6,
																												6)
																										.addGroup(
																												jPanel5Layout
																														.createParallelGroup(
																																javax.swing.GroupLayout.Alignment.LEADING)
																														.addComponent(
																																jButton18,
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																129,
																																javax.swing.GroupLayout.PREFERRED_SIZE)
																														.addComponent(
																																jButton19,
																																javax.swing.GroupLayout.Alignment.TRAILING,
																																javax.swing.GroupLayout.PREFERRED_SIZE,
																																129,
																																javax.swing.GroupLayout.PREFERRED_SIZE)))))
														.addGroup(
																jPanel5Layout
																		.createSequentialGroup()
																		.addGap(155,
																				155,
																				155)
																		.addComponent(
																				jLabel66)))
										.addContainerGap(458, Short.MAX_VALUE)));
		jPanel5Layout
				.setVerticalGroup(jPanel5Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel5Layout
										.createSequentialGroup()
										.addGap(24, 24, 24)
										.addComponent(jLabel66)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel61)
														.addComponent(jButton18)
														.addComponent(
																jTextField32,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(51, 51, 51)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel62)
														.addComponent(jButton19)
														.addComponent(
																jTextField33,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(50, 50, 50)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel63)
														.addComponent(jButton20)
														.addComponent(
																jTextField34,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(72, 72, 72)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel64)
														.addComponent(jButton21)
														.addComponent(
																jTextField35,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addGap(66, 66, 66)
										.addGroup(
												jPanel5Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(jLabel65)
														.addComponent(jButton22)
														.addComponent(
																jTextField36,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(139, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Reports", jPanel5);

		menuAbout.setText("About");

		jMenu4.setText("About");
		menuAbout.add(jMenu4);

		jMenuBar1.add(menuAbout);

		mntmExit = new JMenuItem("Exit");
		menuAbout.add(mntmExit);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1));
		layout.setVerticalGroup(layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				layout.createSequentialGroup()
						.addComponent(jTabbedPane1,
								javax.swing.GroupLayout.PREFERRED_SIZE, 570,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(0, 0, Short.MAX_VALUE)));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton1ActionPerformed



	private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton10ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton10ActionPerformed

	private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton11ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jButton11ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed"
		// desc=" Look and feel setting code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase
		 * /tutorial/uiswing/lookandfeel/plaf.html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
					.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Main.class.getName()).log(
					java.util.logging.Level.SEVERE, null, ex);
		}
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Main().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JButton jButton1;
	private javax.swing.JButton jButton10;
	private javax.swing.JButton jButton11;
	private javax.swing.JButton jButton12;
	private javax.swing.JButton jButton13;
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JButton jButton18;
	private javax.swing.JButton jButton19;
	private javax.swing.JButton jButton2;
	private javax.swing.JButton jButton20;
	private javax.swing.JButton jButton21;
	private javax.swing.JButton jButton22;
	private javax.swing.JButton jButton3;
	private javax.swing.JButton jButton4;
	private javax.swing.JButton btnAddBook;
	private javax.swing.JButton btnEditBook;
	private javax.swing.JButton btnSearchBook;
	private javax.swing.JButton btnDeleteBook;
	private javax.swing.JButton jButton9;
	private javax.swing.JComboBox cbxUserGroup1;
	private javax.swing.JLabel lblUserId1;
	private javax.swing.JLabel jLabel10;
	private javax.swing.JLabel jLabel11;
	private javax.swing.JLabel jLabel12;
	private javax.swing.JLabel lblBookId;
	private javax.swing.JLabel lblSerialNumber;
	private javax.swing.JLabel lblTitle2;
	private javax.swing.JLabel lblAuthor;
	private javax.swing.JLabel lblPublisher;
	private javax.swing.JLabel lblSubject;
	private javax.swing.JLabel lblPages;
	private javax.swing.JLabel lblUserGroup1;
	private javax.swing.JLabel lblSeries;
	private javax.swing.JLabel lblPrice;
	private javax.swing.JLabel lblStatus;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JLabel jLabel26;
	private javax.swing.JLabel jLabel27;
	private javax.swing.JLabel jLabel28;
	private javax.swing.JLabel jLabel29;
	private javax.swing.JLabel lblTitle1;
	private javax.swing.JLabel jLabel30;
	private javax.swing.JLabel jLabel31;
	private javax.swing.JLabel jLabel32;
	private javax.swing.JLabel jLabel33;
	private javax.swing.JLabel jLabel34;
	private javax.swing.JLabel jLabel35;
	private javax.swing.JLabel jLabel36;
	private javax.swing.JLabel jLabel37;
	private javax.swing.JLabel jLabel38;
	private javax.swing.JLabel jLabel39;
	private javax.swing.JLabel lblSex1;
	private javax.swing.JLabel jLabel40;
	private javax.swing.JLabel jLabel41;
	private javax.swing.JLabel jLabel42;
	private javax.swing.JLabel jLabel43;
	private javax.swing.JLabel jLabel44;
	private javax.swing.JLabel jLabel45;
	private javax.swing.JLabel jLabel46;
	private javax.swing.JLabel jLabel47;
	private javax.swing.JLabel jLabel48;
	private javax.swing.JLabel jLabel49;
	private javax.swing.JLabel lblLastName1;
	private javax.swing.JLabel jLabel50;
	private javax.swing.JLabel jLabel51;
	private javax.swing.JLabel jLabel52;
	private javax.swing.JLabel jLabel53;
	private javax.swing.JLabel jLabel54;
	private javax.swing.JLabel jLabel55;
	private javax.swing.JLabel jLabel56;
	private javax.swing.JLabel jLabel57;
	private javax.swing.JLabel jLabel58;
	private javax.swing.JLabel jLabel59;
	private javax.swing.JLabel lblFirstName1;
	private javax.swing.JLabel jLabel60;
	private javax.swing.JLabel jLabel61;
	private javax.swing.JLabel jLabel62;
	private javax.swing.JLabel jLabel63;
	private javax.swing.JLabel jLabel64;
	private javax.swing.JLabel jLabel65;
	private javax.swing.JLabel jLabel66;
	private javax.swing.JLabel lblDOB1;
	private javax.swing.JLabel jLabel8;
	private javax.swing.JLabel jLabel9;
	private javax.swing.JList lisUsers;
	private javax.swing.JMenu menuAbout;
	private javax.swing.JMenu jMenu4;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel pnlUsers;
	private javax.swing.JPanel pnlBooks;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JPanel jPanel4;
	private javax.swing.JPanel jPanel5;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private javax.swing.JScrollPane jScrollPane5;
	private javax.swing.JScrollPane jScrollPane6;
	private javax.swing.JScrollPane jScrollPane7;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTable jTable2;
	private javax.swing.JTable jTable3;
	private javax.swing.JTable jTable4;
	private javax.swing.JTable jTable5;
	private javax.swing.JTable jTable6;
	private javax.swing.JTextField txtUserId1;
	private javax.swing.JTextField jTextField10;
	private javax.swing.JTextField jTextField11;
	private javax.swing.JTextField txtBookId;
	private javax.swing.JTextField txtSerialNumber;
	private javax.swing.JTextField txtTitle2;
	private javax.swing.JTextField txtAuthor;
	private javax.swing.JTextField txtPublisher;
	private javax.swing.JTextField txtSubject;
	private javax.swing.JTextField txtPages;
	private javax.swing.JTextField txtSeries;
	private javax.swing.JTextField txtTitle1;
	private javax.swing.JTextField txtPrice;
	private javax.swing.JTextField txtStatus;
	private javax.swing.JTextField jTextField22;
	private javax.swing.JTextField jTextField23;
	private javax.swing.JTextField jTextField24;
	private javax.swing.JTextField jTextField25;
	private javax.swing.JTextField jTextField26;
	private javax.swing.JTextField jTextField27;
	private javax.swing.JTextField jTextField28;
	private javax.swing.JTextField jTextField29;
	private javax.swing.JTextField txtSex1;
	private javax.swing.JTextField jTextField30;
	private javax.swing.JTextField jTextField31;
	private javax.swing.JTextField jTextField32;
	private javax.swing.JTextField jTextField33;
	private javax.swing.JTextField jTextField34;
	private javax.swing.JTextField jTextField35;
	private javax.swing.JTextField jTextField36;
	private javax.swing.JTextField txtLastName1;
	private javax.swing.JTextField txtFirstName1;
	private javax.swing.JTextField txtDOB;
	private javax.swing.JTextField jTextField7;
	private javax.swing.JTextField jTextField8;
	private javax.swing.JTextField jTextField9;
	private JMenuItem mntmExit;
}
